name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' # specify the Go version

      - name: Extract tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build macOS ARM binary
        run: GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o gepetto-mac-arm-${{ env.TAG_NAME }} gepetto.go

      - name: Build macOS Intel binary
        run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o gepetto-mac-intel-${{ env.TAG_NAME }} gepetto.go

      - name: Build Linux Intel binary
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o gepetto-linux-intel-${{ env.TAG_NAME }} gepetto.go

      - name: Build Windows binary
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o gepetto-windows-${{ env.TAG_NAME }}.exe gepetto.go

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload macOS ARM binary
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Use the custom secret
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./gepetto-mac-arm-${{ env.TAG_NAME }}
            asset_name: gepetto-mac-arm-${{ env.TAG_NAME }}
            asset_content_type: application/octet-stream

      - name: Upload macOS Intel binary
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Use the custom secret
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gepetto-mac-intel-${{ env.TAG_NAME }}
          asset_name: gepetto-mac-intel-${{ env.TAG_NAME }}
          asset_content_type: application/octet-stream

      - name: Upload Linux Intel binary
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Use the custom secret
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gepetto-linux-intel-${{ env.TAG_NAME }}
          asset_name: gepetto-linux-intel-${{ env.TAG_NAME }}
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Use the custom secret
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gepetto-windows-${{ env.TAG_NAME }}.exe
          asset_name: gepetto-windows-${{ env.TAG_NAME }}.exe
          asset_content_type: application/octet-stream
